[package]
name = "rust-utreexo"
version = "0.1.0"
authors = ["bsat <8377116+BSathvik@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_utreexo"
path = "src/lib.rs"


[dependencies]
